baseURL = "https://sdboyer.io/"
languageCode = "en-us"
title = "sdboyer.io"
theme = "slim"
googleAnalytics = "UA-100002759-1"

[params]
    highlight = "github"
    topmenu = "none"
    GithubID = "sdboyer"
    TwitterID = "sdboyer"
    FooterMsg = "ohai"

[author]
    name = "sam boyer"
